clean:
	rm -rf ./**/*.log
	rm task_01
	rm task_02
	rm task_03
	rm task_04
	rm task_04_proc
task_01:
	hbmk2 task_01.prg
	./task_01
	rm task_01
task_02:
	hbmk2 task_02.prg
	./task_02
	rm task_02
task_03:
	hbmk2 task_03.prg
	./task_03
	rm task_03
task_04:
	hbmk2 task_04.prg
	./task_04
	rm task_04
	hbmk2 task_04_proc.prg
	./task_04_proc
	rm task_04_proc