clean:
	rm -f ./**/*.log
	rm -f task_01
	rm -f task_02_01
	rm -f task_02_02
	rm -f task_02_03
	rm -f task_02_04
	rm -f task_02_05
task_01:
	hbmk2 task_01.prg
	./task_01
	rm task_01
task_02: task_02_01 task_02_02 task_02_03 task_02_04 task_02_05
task_02_01:
	hbmk2 task_02_01.prg
	./task_02_01
	rm task_02_01
task_02_02:
	hbmk2 task_02_02.prg
	./task_02_02
	rm task_02_02
task_02_03:
	hbmk2 task_02_03.prg
	./task_02_03
	rm task_02_03
task_02_04:
	hbmk2 task_02_04.prg
	./task_02_04
	rm task_02_04
task_02_05:
	hbmk2 task_02_05.prg
	./task_02_05
	rm task_02_05